# Generated by Django 5.1.6 on 2025-04-22 17:11

import cloudinary.models
import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wakeelapp', '0002_alter_videos_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='videos',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
