# Generated by Django 5.1.6 on 2025-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakeelapp', '0003_alter_blogs_content_alter_blogs_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
